account:
  service:
    version: "v2"
    name: "account-service-dev"
    env: "dev"
    configLoadedFrom: "{cipher}52a7ae983f4e143b94faa42445aea393dcd52cf44af5b361faba17be3747ccd4"

server:
  port: 9012 #Port Configuration

spring:
  application:
    name: "ACCOUNTS-SERVICE-DEV"
