account:
  service:
    version: "v1"
    name: "account-service-dev"
    env: "dev"
    configLoadedFrom: "{cipher}0add2eb9b5627c7cce39fa2bcc1afc9aa61ab4cc1b88a0ab28e4ee0d29af300e"

server:
  port: 9012 #Port Configuration

spring:
  application:
    name: "ACCOUNTS-SERVICE-DEV"
