account:
  service:
    version: "v1"
    name: "account-service-prod"
    env: "prod"
    configLoadedFrom: "{cipher}e1a278e2196af545160ca34462c4351088a8ef979fa6ef5b5abd5a9f420a98a1"

server:
  port: 9012 #Port Configuration

spring:
  application:
    name: "ACCOUNTS-SERVICE-PROD"
