loan:
  service:
    version: "v1"
    name: "loans-service-prod"
    env: "prod"
    configLoadedFrom: "classPath-prod"

server:
  port: 9013 #Port Configuration

spring:
  application:
    name: "LOANS-SERVICE-PROD" #Application Name
